### ISSUE TITLE
As a user, I want to be able to login to my account

### ISSUE THREAD

**Issue by MetteMunch** [ellebyberg/WishlistMMMD#13]

**Comment by DanielJensenKEA** [comment]
Bruge sessions til at sørge for at kræve login. Tilmed krav om login ved alle andre endpoints. Nytter ikke noget at bede om login, hvis man alligevel kan tilgå øvrige endpoints gennem url. 

Man kan give session en boolean værdi for at tjekke, om hvorvidt brugeren er 'logged in' for at være i stand til at tilgå endpoints.
